/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    P2PLending: {
      address:
        "0x07e387442840109a6faab4521cdae47603a1df5432eca19da50812829f8edeac",
      abi: [
        {
          type: "impl",
          name: "P2PLendingImpl",
          interface_name: "contracts::P2PLending::IP2PLendingTrait",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::P2PLending::IP2PLendingTrait",
          items: [
            {
              type: "function",
              name: "request_loan",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "interest_rate",
                  type: "core::integer::u256",
                },
                {
                  name: "deadlineForFund",
                  type: "core::integer::u64",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "fund_loan",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "repay_loan",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "register",
              inputs: [
                {
                  name: "name",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_username",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_loan_borrower",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_loan_token",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_loan_amount",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_loan_repay_amount",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_loan_funded_amount",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_loan_fund_deadline",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_loan_interest",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_loan_status",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u8",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_loan_count",
              inputs: [],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_funder_funded_amount",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
                {
                  name: "funder",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_funders_in_loan_counter",
              inputs: [
                {
                  name: "loan_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::P2PLending::P2PLending::LoanRequest",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "token",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "interest_rate",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::P2PLending::P2PLending::UserRegistration",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "name",
              type: "core::byte_array::ByteArray",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::P2PLending::P2PLending::FundLoan",
          kind: "struct",
          members: [
            {
              name: "funder",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "loanId",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::P2PLending::P2PLending::RepayLoan",
          kind: "struct",
          members: [
            {
              name: "repayer",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "receiver",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "loanId",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::P2PLending::P2PLending::Event",
          kind: "enum",
          variants: [
            {
              name: "LoanRequest",
              type: "contracts::P2PLending::P2PLending::LoanRequest",
              kind: "nested",
            },
            {
              name: "UserRegistration",
              type: "contracts::P2PLending::P2PLending::UserRegistration",
              kind: "nested",
            },
            {
              name: "FundLoan",
              type: "contracts::P2PLending::P2PLending::FundLoan",
              kind: "nested",
            },
            {
              name: "RepayLoan",
              type: "contracts::P2PLending::P2PLending::RepayLoan",
              kind: "nested",
            },
          ],
        },
      ],
    },
  },
} as const;

export default deployedContracts;
